import SliderImg1 from './WallpaperDog-10915549.jpg';
import SliderImg2 from './WallpaperDog-5536736.jpg';
import SliderImg3 from './WallpaperDog-10915526.jpg';
import logo from  './overview_apple_music_logo_medium.png';
import BeatsImg from './WallpaperDog-10915418.jpg';
import TrialImg from './WallpaperDog-10915368.jpg';
import RangersImg from './WallpaperDog-10915266.jpg';
import GostBalloonImg from './WallpaperDog-697338.jpg';
import ExclusivesImg from './wp9049761-films-4k-wallpapers.jpg';
import PlaylistsImg from './wp5242984-dark-movie-wallpapers.jpg';
import Cartoon from './cartoon.jpg'
import Cartoon1 from './cartoon1.jpg';
import Cartoon3 from './cartoon3.jpg';
import Cartoon4 from './cartoon4.jpg';
import Cartoon5 from './cartoon5.jpg';
import Cartoon6 from './cartoon6.jpg';
import Cartoon7 from './cartoon7.jpg';
import Cartoon8 from './cartoon8.jpg';
import Cartoon9 from './cartoon9.jpg';
import Cartoon10 from './cartoon10.jpg';
import Cartoon12 from './cartoon12.jpg';
import Actor1 from './actor1.jpg';
import Actor2 from './actor2.jpg';
import DvdImg from './dvd-image.jpg';
import SearchIcon1 from './search-icon1.gif';
import SearchIcon2 from './search-icon3.png';
import video from './login.mp4';
import NavCompassIcon from './compasses.png';
// import LoginBackgroungImg from './login-backgoround.jpg'
import LoginBackgroungImg from './login-backgoround7.jpg';
import DvdImg2 from './dvdImg.jpg';
import AvtarImg from './avtar2.gif';
import AddUserImg from './add.png';
import CrossImg from './cross.png';
export {SliderImg1, SliderImg2, SliderImg3, SearchIcon1, AvtarImg, DvdImg, DvdImg2, AddUserImg, CrossImg, NavCompassIcon, SearchIcon2, video,LoginBackgroungImg, logo, RangersImg, Actor1,Actor2, GostBalloonImg, ExclusivesImg, PlaylistsImg, BeatsImg, TrialImg,Cartoon, Cartoon1, Cartoon3, Cartoon4, Cartoon5, Cartoon6,Cartoon7,Cartoon8,Cartoon9, Cartoon10, Cartoon12}
